In [1]:
import numpy as np

## Broadcasting

In [2]:
arr = np.zeros((5,5))

In [3]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
row = np.array([7,8,9,4,6])

In [5]:
row

array([7, 8, 9, 4, 6])

In [6]:
arr.shape

(5, 5)

In [7]:
row.shape

(5,)

In [8]:
arr + row

array([[7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.]])

In [9]:
column = np.array([[1,3,4,6,2]])

In [10]:
column.shape

(1, 5)

In [11]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
column.T + arr

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2.]])

## Array Manipulation

In [13]:
arr1 = np.random.randint(1,20,(4,5))

In [14]:
arr1

array([[ 1, 17,  9,  9,  8],
       [15,  3, 10,  2,  9],
       [13,  5, 17,  6,  7],
       [11, 16,  5,  1, 19]])

In [15]:
arr1.shape

(4, 5)

In [16]:
arr1.size

20

In [17]:
arr1.reshape(10,2)

array([[ 1, 17],
       [ 9,  9],
       [ 8, 15],
       [ 3, 10],
       [ 2,  9],
       [13,  5],
       [17,  6],
       [ 7, 11],
       [16,  5],
       [ 1, 19]])

In [18]:
arr1.transpose()

array([[ 1, 15, 13, 11],
       [17,  3,  5, 16],
       [ 9, 10, 17,  5],
       [ 9,  2,  6,  1],
       [ 8,  9,  7, 19]])

In [19]:
arr1.T

array([[ 1, 15, 13, 11],
       [17,  3,  5, 16],
       [ 9, 10, 17,  5],
       [ 9,  2,  6,  1],
       [ 8,  9,  7, 19]])

In [20]:
s=arr1.flatten()

In [21]:
s

array([ 1, 17,  9,  9,  8, 15,  3, 10,  2,  9, 13,  5, 17,  6,  7, 11, 16,
        5,  1, 19])

In [22]:
s.shape

(20,)

In [23]:
arr2 = np.array([1,2,4,4,5])

In [24]:
arr2.ndim

1

In [29]:
n=np.expand_dims(arr2,axis=1)

In [30]:
n.shape

(5, 1)

In [31]:
m = np.expand_dims(arr2, axis=0)

In [32]:
arr2.shape

(5,)

In [33]:
m.shape

(1, 5)

In [34]:
mat = np.array([[2],[5],[6]])

In [35]:
mat

array([[2],
       [5],
       [6]])

In [36]:
mat.shape

(3, 1)

In [37]:
mat.squeeze()

array([2, 5, 6])

In [38]:
sq = np.squeeze(mat)

In [39]:
sq

array([2, 5, 6])

In [40]:
sq.shape

(3,)

In [41]:
arr2

array([1, 2, 4, 4, 5])

In [42]:
np.repeat(arr2,3)

array([1, 1, 1, 2, 2, 2, 4, 4, 4, 4, 4, 4, 5, 5, 5])

In [43]:
np.diagonal(arr)

array([0., 0., 0., 0., 0.])

In [44]:
arr3 = np.array([1,5,6,8,7])

In [45]:
np.diag(arr3)

array([[1, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 7]])

## Binary Operation

In [51]:
arr1 = np.random.randint(1,10,(4,3))
arr2 = np.random.randint(1,10,(4,3))

In [52]:
arr1

array([[2, 7, 1],
       [6, 6, 4],
       [8, 6, 9],
       [2, 7, 6]])

In [53]:
arr2

array([[8, 3, 6],
       [1, 4, 7],
       [9, 3, 1],
       [7, 8, 8]])

In [55]:
arr1 & arr2

array([[0, 3, 0],
       [0, 4, 4],
       [8, 2, 1],
       [2, 0, 0]])

In [56]:
arr1 | arr2

array([[10,  7,  7],
       [ 7,  6,  7],
       [ 9,  7,  9],
       [ 7, 15, 14]])

In [57]:
~arr2

array([[ -9,  -4,  -7],
       [ -2,  -5,  -8],
       [-10,  -4,  -2],
       [ -8,  -9,  -9]])

In [58]:
arr1 * arr2

array([[16, 21,  6],
       [ 6, 24, 28],
       [72, 18,  9],
       [14, 56, 48]])

In [59]:
arr1 + arr2


array([[10, 10,  7],
       [ 7, 10, 11],
       [17,  9, 10],
       [ 9, 15, 14]])

In [60]:
arr1 - arr2

array([[-6,  4, -5],
       [ 5,  2, -3],
       [-1,  3,  8],
       [-5, -1, -2]])

## Numpy String Function

In [63]:
arr = np.array(['datascience','machinelearning'])

In [64]:
arr

array(['datascience', 'machinelearning'], dtype='<U15')

In [65]:
np.char.upper(arr)

array(['DATASCIENCE', 'MACHINELEARNING'], dtype='<U15')

In [66]:
np.char.title(arr)

array(['Datascience', 'Machinelearning'], dtype='<U15')

In [67]:
np.char.split(arr)

array([list(['datascience']), list(['machinelearning'])], dtype=object)

## Mathematical Functions

In [68]:
arr1

array([[2, 7, 1],
       [6, 6, 4],
       [8, 6, 9],
       [2, 7, 6]])

In [69]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.84147098],
       [-0.2794155 , -0.2794155 , -0.7568025 ],
       [ 0.98935825, -0.2794155 ,  0.41211849],
       [ 0.90929743,  0.6569866 , -0.2794155 ]])

In [70]:
np.cos(arr1)

array([[-0.41614684,  0.75390225,  0.54030231],
       [ 0.96017029,  0.96017029, -0.65364362],
       [-0.14550003,  0.96017029, -0.91113026],
       [-0.41614684,  0.75390225,  0.96017029]])

In [71]:
np.tan(arr1)

array([[-2.18503986,  0.87144798,  1.55740772],
       [-0.29100619, -0.29100619,  1.15782128],
       [-6.79971146, -0.29100619, -0.45231566],
       [-2.18503986,  0.87144798, -0.29100619]])

In [72]:
np.tanh(arr1)

array([[0.96402758, 0.99999834, 0.76159416],
       [0.99998771, 0.99998771, 0.9993293 ],
       [0.99999977, 0.99998771, 0.99999997],
       [0.96402758, 0.99999834, 0.99998771]])

In [73]:
np.log10(arr1)

array([[0.30103   , 0.84509804, 0.        ],
       [0.77815125, 0.77815125, 0.60205999],
       [0.90308999, 0.77815125, 0.95424251],
       [0.30103   , 0.84509804, 0.77815125]])

In [74]:
np.sqrt(arr1)

array([[1.41421356, 2.64575131, 1.        ],
       [2.44948974, 2.44948974, 2.        ],
       [2.82842712, 2.44948974, 3.        ],
       [1.41421356, 2.64575131, 2.44948974]])

In [75]:
np.power(arr1,2)

array([[ 4, 49,  1],
       [36, 36, 16],
       [64, 36, 81],
       [ 4, 49, 36]], dtype=int32)

In [76]:
np.mean(arr1)

5.333333333333333

In [77]:
np.median(arr1)

6.0

In [78]:
np.std(arr1)

2.4267032964268394

In [79]:
np.var(arr1)

5.888888888888889

In [80]:
np.max(arr1)

9

In [81]:
np.min(arr1)

1

## Linear Algebra

In [82]:
arr1

array([[2, 7, 1],
       [6, 6, 4],
       [8, 6, 9],
       [2, 7, 6]])

In [90]:
arr3=np.random.randint(1,10,(3,4))

In [91]:
arr3

array([[6, 4, 9, 7],
       [5, 1, 1, 9],
       [6, 6, 1, 5]])

In [92]:
np.dot(arr1, arr3)

array([[ 53,  21,  26,  82],
       [ 90,  54,  64, 116],
       [132,  92,  87, 155],
       [ 83,  51,  31, 107]])

In [93]:
arr1@arr3

array([[ 53,  21,  26,  82],
       [ 90,  54,  64, 116],
       [132,  92,  87, 155],
       [ 83,  51,  31, 107]])

In [94]:
arr1

array([[2, 7, 1],
       [6, 6, 4],
       [8, 6, 9],
       [2, 7, 6]])

In [98]:
arr1 = np.random.randint(1,4,(4,4))

In [99]:
arr1

array([[2, 2, 3, 2],
       [1, 3, 3, 3],
       [3, 1, 1, 2],
       [2, 2, 3, 3]])

In [100]:
np.linalg.inv(arr1)

array([[ 0.375, -0.125,  0.375, -0.375],
       [ 0.375,  0.875,  0.375, -1.375],
       [ 0.5  , -0.5  , -0.5  ,  0.5  ],
       [-1.   ,  0.   ,  0.   ,  1.   ]])

In [101]:
np.linalg.det(arr1)

-8.000000000000002

In [102]:
matrix = np.matrix([[2,4],[5,6]])

In [103]:
matrix

matrix([[2, 4],
        [5, 6]])

In [104]:
np.linalg.det(matrix)

-7.999999999999998

In [105]:
# Solve a sytem linear equations Ax=b
A = np.array([[2,1],[1,-3]])
B = np.array([8,-3])

In [106]:
equation = np.linalg.solve(A,B)

In [107]:
equation

array([3., 2.])

## Sort and Searching

In [108]:
arr = np.array([4,5,6,8,45,45,78,12,3,5,8])

In [109]:
arr

array([ 4,  5,  6,  8, 45, 45, 78, 12,  3,  5,  8])

In [110]:
np.sort(arr)

array([ 3,  4,  5,  5,  6,  8,  8, 12, 45, 45, 78])

In [111]:
np.searchsorted(arr,45)

4

In [112]:
np.searchsorted(arr,4)

0

In [113]:
np.where(arr>8)

(array([4, 5, 6, 7], dtype=int64),)

In [114]:
np.extract(arr>8,arr)

array([45, 45, 78, 12])